[package]
name = "sol_prng"
version = "1.1.1"
edition = "2021"
description = """
A simple functional pseudo random number generator.
No mutability. Relies on shadowing as of now.
"""
authors = ["mateusqqfoi"]
rust-version = "1.62.0"
license = "MIT"

[dependencies]
